import type { DashboardData } from "@/lib/types";

const units = [
  {
    id: "unit-1",
    property_name: "North Bridge Shophouse",
    unit_label: "#02-04",
    address: "12 North Bridge Road",
    notes: "Retail tenancy with shared riser access",
  },
  {
    id: "unit-2",
    property_name: "River Valley Offices",
    unit_label: "08-12",
    address: "240 River Valley Road",
    notes: "Office suite with pantry plumbing",
  },
];

const tenants = [
  {
    id: "tenant-1",
    tenant_name: "Alicia Tan",
    company_name: "Pine & Paper Studio",
    phone_number: "+65 9123 4567",
    normalized_phone: "6591234567",
    unit_id: "unit-1",
    lease_status: "active",
    notes: "Prefers WhatsApp for maintenance updates",
    unit: units[0],
  },
  {
    id: "tenant-2",
    tenant_name: "Marcus Lim",
    company_name: "Lattice Works Pte Ltd",
    phone_number: "+65 9788 2100",
    normalized_phone: "6597882100",
    unit_id: "unit-2",
    lease_status: "active",
    notes: "Office manager is usually on-site after 10am",
    unit: units[1],
  },
];

const conversations = [
  {
    id: "conversation-1",
    wa_id: "6591234567",
    tenant_phone: "+65 9123 4567",
    contact_name: "Alicia Tan",
    tenant_id: "tenant-1",
    unit_id: "unit-1",
    status: "open",
    last_message_at: new Date().toISOString(),
    last_message_preview: "Water is dripping under the pantry sink.",
    tenant: tenants[0],
    unit: units[0],
  },
  {
    id: "conversation-2",
    wa_id: "6599990000",
    tenant_phone: "+65 9999 0000",
    contact_name: "Unknown tenant",
    tenant_id: null,
    unit_id: null,
    status: "open",
    last_message_at: new Date(Date.now() - 1000 * 60 * 58).toISOString(),
    last_message_preview: "The corridor light outside our door is flickering.",
    tenant: null,
    unit: null,
  },
];

const messages = [
  {
    id: "message-1",
    conversation_id: "conversation-1",
    direction: "inbound" as const,
    whatsapp_message_id: "wamid.demo.1",
    message_type: "text",
    body: "Hi, water is dripping under the pantry sink. Can someone check today?",
    media_id: null,
    media_mime_type: null,
    media_sha256: null,
    storage_bucket: null,
    storage_path: null,
    media_url: null,
    delivery_status: "received",
    error_message: null,
    sent_by_staff_id: null,
    created_at: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
  },
  {
    id: "message-2",
    conversation_id: "conversation-1",
    direction: "inbound" as const,
    whatsapp_message_id: "wamid.demo.2",
    message_type: "image",
    body: "Photo attached",
    media_id: "media.demo",
    media_mime_type: "image/svg+xml",
    media_sha256: null,
    storage_bucket: "maintenance-media",
    storage_path: "demo/leak.svg",
    media_url: "/sample-leak.svg",
    delivery_status: "received",
    error_message: null,
    sent_by_staff_id: null,
    created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
  },
  {
    id: "message-3",
    conversation_id: "conversation-1",
    direction: "outbound" as const,
    whatsapp_message_id: "wamid.demo.3",
    message_type: "text",
    body: "Thanks Alicia. We created a maintenance ticket and are assigning it now.",
    media_id: null,
    media_mime_type: null,
    media_sha256: null,
    storage_bucket: null,
    storage_path: null,
    media_url: null,
    delivery_status: "sent",
    error_message: null,
    sent_by_staff_id: "staff-1",
    created_at: new Date(Date.now() - 1000 * 60 * 7).toISOString(),
  },
];

const staff = [
  {
    user_id: "staff-1",
    full_name: "Jamie Ops",
    role: "manager",
    email: "jamie@example.com",
  },
  {
    user_id: "staff-2",
    full_name: "Rina Lee",
    role: "on_site",
    email: "rina@example.com",
  },
  {
    user_id: "staff-3",
    full_name: "Daniel Koh",
    role: "on_site",
    email: "daniel@example.com",
  },
  {
    user_id: "staff-4",
    full_name: "Mei Wong",
    role: "on_site",
    email: "mei@example.com",
  },
];

const tickets = [
  {
    id: "ticket-1",
    ticket_number: 1001,
    title: "Pantry sink leak",
    description: "Tenant reported active dripping under pantry sink via WhatsApp.",
    tenant_id: "tenant-1",
    unit_id: "unit-1",
    source_conversation_id: "conversation-1",
    source_message_id: "message-2",
    attached_images: [
      { bucket: "maintenance-media", path: "demo/leak.svg", type: "image/svg+xml" },
    ],
    priority: "high" as const,
    status: "assigned" as const,
    assigned_staff_id: "staff-2",
    created_by_staff_id: "staff-1",
    created_at: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    tenant: tenants[0],
    unit: units[0],
  },
];

export function getDemoDashboardData(): DashboardData {
  return {
    configured: false,
    demo: true,
    user: staff[0],
    conversations,
    selectedConversation: conversations[0],
    messages,
    tenants,
    units,
    tickets,
    ticketUpdates: [
      {
        id: "update-1",
        ticket_id: "ticket-1",
        actor_staff_id: "staff-1",
        update_type: "created",
        body: "Created from WhatsApp image message.",
        from_status: null,
        to_status: "open",
        created_at: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
      },
      {
        id: "update-2",
        ticket_id: "ticket-1",
        actor_staff_id: "staff-1",
        update_type: "assigned",
        body: "Assigned to Rina Lee.",
        from_status: "open",
        to_status: "assigned",
        created_at: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
      },
    ],
    staff,
    auditLogs: [
      {
        id: "audit-1",
        actor_staff_id: null,
        action: "whatsapp.message.received",
        entity_type: "whatsapp_message",
        entity_id: "message-2",
        metadata: { message_type: "image" },
        created_at: new Date(Date.now() - 1000 * 60 * 10).toISOString(),
      },
      {
        id: "audit-2",
        actor_staff_id: "staff-1",
        action: "maintenance.ticket.created",
        entity_type: "maintenance_ticket",
        entity_id: "ticket-1",
        metadata: { source_message_id: "message-2" },
        created_at: new Date(Date.now() - 1000 * 60 * 6).toISOString(),
      },
    ],
    setupIssues: [
      "Demo mode: add Supabase and WhatsApp environment variables to enable live data.",
    ],
  };
}
