create extension if not exists pgcrypto;

create type public.lease_status as enum ('active', 'ending_soon', 'expired', 'past_due');
create type public.whatsapp_message_direction as enum ('inbound', 'outbound');
create type public.maintenance_ticket_priority as enum ('low', 'normal', 'high', 'urgent');
create type public.maintenance_ticket_status as enum (
  'open',
  'triaging',
  'assigned',
  'waiting_for_vendor',
  'waiting_for_tenant',
  'resolved',
  'closed'
);

create table public.units (
  id uuid primary key default gen_random_uuid(),
  property_name text not null,
  unit_label text not null,
  address text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (property_name, unit_label)
);

create table public.tenants (
  id uuid primary key default gen_random_uuid(),
  tenant_name text not null,
  company_name text,
  phone_number text not null,
  normalized_phone text not null,
  unit_id uuid references public.units(id) on delete set null,
  lease_status public.lease_status not null default 'active',
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (normalized_phone)
);

create table public.staff_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  role text not null default 'staff',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.whatsapp_conversations (
  id uuid primary key default gen_random_uuid(),
  wa_id text not null,
  tenant_phone text not null,
  contact_name text,
  tenant_id uuid references public.tenants(id) on delete set null,
  unit_id uuid references public.units(id) on delete set null,
  status text not null default 'open',
  last_message_at timestamptz,
  last_message_preview text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (wa_id)
);

create table public.whatsapp_messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.whatsapp_conversations(id) on delete cascade,
  direction public.whatsapp_message_direction not null,
  whatsapp_message_id text,
  message_type text not null,
  body text,
  media_id text,
  media_mime_type text,
  media_sha256 text,
  storage_bucket text,
  storage_path text,
  delivery_status text not null default 'received',
  error_message text,
  sent_by_staff_id uuid references auth.users(id) on delete set null,
  raw_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create unique index whatsapp_messages_provider_id_unique
  on public.whatsapp_messages (whatsapp_message_id)
  where whatsapp_message_id is not null;

create table public.maintenance_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity unique,
  title text not null,
  description text,
  tenant_id uuid references public.tenants(id) on delete set null,
  unit_id uuid references public.units(id) on delete set null,
  source_conversation_id uuid references public.whatsapp_conversations(id) on delete set null,
  source_message_id uuid references public.whatsapp_messages(id) on delete set null,
  attached_images jsonb not null default '[]'::jsonb,
  priority public.maintenance_ticket_priority not null default 'normal',
  status public.maintenance_ticket_status not null default 'open',
  assigned_staff_id uuid references auth.users(id) on delete set null,
  created_by_staff_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table public.maintenance_ticket_updates (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.maintenance_tickets(id) on delete cascade,
  actor_staff_id uuid references auth.users(id) on delete set null,
  update_type text not null,
  body text,
  from_status public.maintenance_ticket_status,
  to_status public.maintenance_ticket_status,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_staff_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index tenants_unit_id_idx on public.tenants(unit_id);
create index conversations_tenant_id_idx on public.whatsapp_conversations(tenant_id);
create index conversations_last_message_idx on public.whatsapp_conversations(last_message_at desc nulls last);
create index messages_conversation_created_idx on public.whatsapp_messages(conversation_id, created_at);
create index tickets_status_idx on public.maintenance_tickets(status);
create index tickets_assigned_staff_idx on public.maintenance_tickets(assigned_staff_id);
create index ticket_updates_ticket_idx on public.maintenance_ticket_updates(ticket_id, created_at);
create index audit_logs_created_idx on public.audit_logs(created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger set_units_updated_at
  before update on public.units
  for each row execute function public.set_updated_at();

create trigger set_tenants_updated_at
  before update on public.tenants
  for each row execute function public.set_updated_at();

create trigger set_staff_users_updated_at
  before update on public.staff_users
  for each row execute function public.set_updated_at();

create trigger set_whatsapp_conversations_updated_at
  before update on public.whatsapp_conversations
  for each row execute function public.set_updated_at();

create trigger set_maintenance_tickets_updated_at
  before update on public.maintenance_tickets
  for each row execute function public.set_updated_at();

alter table public.units enable row level security;
alter table public.tenants enable row level security;
alter table public.staff_users enable row level security;
alter table public.whatsapp_conversations enable row level security;
alter table public.whatsapp_messages enable row level security;
alter table public.maintenance_tickets enable row level security;
alter table public.maintenance_ticket_updates enable row level security;
alter table public.audit_logs enable row level security;

create policy "Authenticated staff can read units"
  on public.units for select to authenticated using (true);
create policy "Authenticated staff can manage units"
  on public.units for all to authenticated using (true) with check (true);

create policy "Authenticated staff can read tenants"
  on public.tenants for select to authenticated using (true);
create policy "Authenticated staff can manage tenants"
  on public.tenants for all to authenticated using (true) with check (true);

create policy "Authenticated staff can read staff profiles"
  on public.staff_users for select to authenticated using (true);
create policy "Authenticated staff can manage staff profiles"
  on public.staff_users for all to authenticated using (true) with check (true);

create policy "Authenticated staff can read conversations"
  on public.whatsapp_conversations for select to authenticated using (true);
create policy "Authenticated staff can manage conversations"
  on public.whatsapp_conversations for all to authenticated using (true) with check (true);

create policy "Authenticated staff can read messages"
  on public.whatsapp_messages for select to authenticated using (true);
create policy "Authenticated staff can manage messages"
  on public.whatsapp_messages for all to authenticated using (true) with check (true);

create policy "Authenticated staff can read tickets"
  on public.maintenance_tickets for select to authenticated using (true);
create policy "Authenticated staff can manage tickets"
  on public.maintenance_tickets for all to authenticated using (true) with check (true);

create policy "Authenticated staff can read ticket updates"
  on public.maintenance_ticket_updates for select to authenticated using (true);
create policy "Authenticated staff can manage ticket updates"
  on public.maintenance_ticket_updates for all to authenticated using (true) with check (true);

create policy "Authenticated staff can read audit logs"
  on public.audit_logs for select to authenticated using (true);
create policy "Authenticated staff can insert audit logs"
  on public.audit_logs for insert to authenticated with check (true);

grant usage on schema public to authenticated, service_role;
grant select, insert, update on public.units to authenticated;
grant select, insert, update on public.tenants to authenticated;
grant select, insert, update on public.staff_users to authenticated;
grant select, insert, update on public.whatsapp_conversations to authenticated;
grant select, insert, update on public.whatsapp_messages to authenticated;
grant select, insert, update on public.maintenance_tickets to authenticated;
grant select, insert, update on public.maintenance_ticket_updates to authenticated;
grant select, insert on public.audit_logs to authenticated;

grant all privileges on public.units to service_role;
grant all privileges on public.tenants to service_role;
grant all privileges on public.staff_users to service_role;
grant all privileges on public.whatsapp_conversations to service_role;
grant all privileges on public.whatsapp_messages to service_role;
grant all privileges on public.maintenance_tickets to service_role;
grant all privileges on public.maintenance_ticket_updates to service_role;
grant all privileges on public.audit_logs to service_role;
grant usage, select on sequence public.maintenance_tickets_ticket_number_seq to authenticated, service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'maintenance-media',
  'maintenance-media',
  false,
  26214400,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'video/mp4',
    'video/quicktime',
    'video/3gpp'
  ]::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Authenticated staff can read maintenance media"
  on storage.objects for select to authenticated
  using (bucket_id = 'maintenance-media');

create policy "Authenticated staff can upload maintenance media"
  on storage.objects for insert to authenticated
  with check (bucket_id = 'maintenance-media');

create policy "Authenticated staff can update maintenance media"
  on storage.objects for update to authenticated
  using (bucket_id = 'maintenance-media')
  with check (bucket_id = 'maintenance-media');
